### ISSUE TITLE
Partners Duplicate Carousel

### ISSUE THREAD

**Issue by klamberth27** [paranet/paranet.github.io#10]
Add our other partners on 2nd and 3rd carousel.

 On the managed services page the scrolling vendor logos at the bottom have the same logos repeated

**Comment by jihaia** [comment]
Do we have more to add or shall I just hide pages 2 and 3?

**Comment by klamberth27** [comment]
Rapid7
Dell
Microsoft
Vmware
Citrix
Cisco
Riverbed
Solarwinds
Sailpoint
FireEye
Adobe

**Comment by jihaia** [comment]
I put enough for a second page - can add a third when we have a couple more.

**Comment by klamberth27** [comment]
Adding
Proofpoint
Egnyte
