### ISSUE TITLE
Cyber Security Lorem Ipsum

### ISSUE THREAD

**Issue by klamberth27** [paranet/paranet.github.io#6]
Need to update the lorem ipsum stuff on cybersecurity.  Did alison send you the pdf’s like the attached?

http://www.paranet.com/services/cybersecurity.html

Monitoring and protecting more than 1,800 networks, we’ve prevented an estimated 1
billion attacks. As a result, we already know which attacks and strategies are most
commonly used against organizations like yours. In security, experience counts.

**Comment by jihaia** [comment]
Alison did send PDFs which is sprinkled throughout the site. She indicated you might have some notes for this particular section.

**Comment by jihaia** [comment]
I've hidden the lorem ipsum text for now - if you have something to add i will.

**Comment by klamberth27** [comment]
Monitoring and protecting more than 1,800 networks, we’ve prevented an estimated 1
billion attacks. As a result, we already know which attacks and strategies are most
commonly used against organizations like yours. In security, experience counts.

**Comment by klamberth27** [comment]
looks good.

**Comment by jihaia** [comment]
Text replaced - looks good.
