### ISSUE TITLE
Replace SendGrid service with Paranet MailGun

### ISSUE THREAD

**Issue by jihaia** [paranet/paranet.github.io#9]
Service needs to be updated with Paranet Mail Gun keys. We have the API key but need the mapped subdomain - cannot use the sandboxed subdomain.

**Comment by klamberth27** [comment]
![image](https://cloud.githubusercontent.com/assets/3837961/24593785/3dd4bf5a-17ec-11e7-80f9-459e7830132c.png)

**Comment by klamberth27** [comment]
Verified

**Comment by jihaia** [comment]
EmailJS service updated with MailGun details.
